image: "maven:3.3.9-jdk-8"
services:
   - "mysql:5.7"
maven-build:
   script: "mvn package"
   stage: build
maven-test:
   script: "mvn test"
   stage: test
stages:
   - test
   - build
variables:
   MYSQL_DATABASE: sys
   MYSQL_HOST: ip-172-31-92-63
   MYSQL_USER: app-root
   MYSQL_PASSWORD: root
   MYSQL_ROOT_PASSWORD: root
