spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/userdb?createDatabaseIfNotExist=true
    username: root
    password: newpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080